*! test_step28.do -- easi 2.0.0: the influence of the imputation of the prices
*! (pimpute()) on the analytic standard errors, against brute forces saved
*! in tests/data/pimpute_bf_*.mmat (U_h = d theta / d w_h, the whole
*! procedure re-run with the weight of each household at 1 +/- 0.01,
*! imputation included; the standard error sqrt(n/(n-1) sum U_h^2)).
*!   a. usual engine: the perfect EASI DGP (3 goods, 1,000 households),
*!      groups of 25 in regions of 10, 20% of lp1 and lp2 missing at random,
*!      every lp1 of groups 1-2 (filled from the region), none in groups
*!      39-40; pimpute(grp region), vce(robust).  Without the term the
*!      standard errors were 0.991-1.002 of the brute force; with it
*!      0.998-1.002 (the floor of easi on the same data without a missing
*!      price: 0.999-1.001).
*!   b. with selection: the censored DGP, the prices of the non-buyers
*!      missing (unit values), lp1 of groups 1-2 missing, groups 39-40 with
*!      every price; selection selvars(w1: q1 ; w2: q2).  Without the term
*!      the standard errors of some elasticities were 9% too large; with it
*!      0.998-1.000.
*! The check takes seconds.  The brute forces are regenerated by
*!   do test_step28.do bf a            (about two minutes)
*!   do test_step28.do bf b first last k   (a block; 1,000 households in
*!                                      four blocks: about four minutes each)
args mode case a1 a2 a3
clear all
set more off
* ---- run this from the replication/ directory ----------------------------
* Every script locates the module (../src), the data (../examples) and the
* frozen R reference (R_reference/out) relative to the current directory:
*     cd <path-to-repository>/replication
*     do Section6-1_pimpute_bruteforce.do
* Nothing needs to be edited.  The check below stops with a clear message
* when the working directory is not replication/.
capture confirm file "master.do"
if _rc {
	di as error "run this script from the replication/ directory:"
	di as error "    cd <path-to-repository>/replication"
	exit 601
}
local ROOT = subinstr("`c(pwd)'", "\", "/", .) + "/.."
local DATA "`ROOT'/replication/pimpute_reference"
adopath ++ "`ROOT'/src"
run "`ROOT'/replication/dgp_easi.do"

global NFAIL 0
capture program drop _chk
program define _chk
	args label value tol
	if (`value' <= `tol') di as txt "  ok    " as res %10.3g `value' as txt "  `label'"
	else {
		di as err "  FAIL  " %10.3g `value' "  `label' (tolerance `tol')"
		global NFAIL = ${NFAIL} + 1
	}
end

* the data of each case
capture program drop _t28data
program define _t28data
	args case
	if "`case'" == "a" {
		quietly easi_dgp, n(1000) seed(20260929)
		quietly {
			gen long id = _n
			gen int grp = ceil(_n / 25)
			gen byte region = ceil(grp / 10)
			set seed 1
			gen double u1 = runiform()
			gen double u2 = runiform()
			replace lp1 = . if (u1 < .2 | inlist(grp, 1, 2)) & !inlist(grp, 39, 40)
			replace lp2 = . if u2 < .2 & !inlist(grp, 39, 40)
			gen double w = 1
		}
		global T28SPEC "w1 w2 w3 [iw = w], lnprices(lp1 lp2 lp3) lnexpenditure(lx) demographics(z1 z2) power(2) pimpute(grp region) vce(robust) compensated notable nolog tolerance(1e-14) iterate(1000)"
	}
	else {
		quietly easi_dgp, n(1000) seed(20260929) censor
		quietly {
			gen long id = _n
			gen int grp = ceil(_n / 25)
			gen byte region = ceil(grp / 10)
			replace lp1 = . if (w1 == 0 | inlist(grp, 1, 2)) & !inlist(grp, 39, 40)
			replace lp2 = . if w2 == 0 & !inlist(grp, 39, 40)
			gen double w = 1
		}
		global T28SPEC "w1 w2 w3 [iw = w], lnprices(lp1 lp2 lp3) lnexpenditure(lx) demographics(z1 z2) power(2) pimpute(grp region) selection selvars(w1: q1 ; w2: q2) vce(robust) compensated notable nolog tolerance(1e-14) iterate(1000)"
	}
end

* the prices filled by hand as pimpute(grp region) fills them: the weighted
* mean of the observed log prices of the group, else of the region.  With
* them as data, easi gives the same estimates and the standard errors
* without the influence of the imputation.
capture program drop _t28fill
program define _t28fill
	foreach v in lp1 lp2 {
		tempvar o
		quietly gen double `o' = `v'
		foreach g in grp region {
			tempvar num den
			quietly egen double `num' = total(cond(!missing(`o'), w * `o', .)), by(`g')
			quietly egen double `den' = total(cond(!missing(`o'), w, .)), by(`g')
			quietly replace `v' = `num' / `den' if missing(`v') & `den' > 0 & !missing(`den')
			drop `num' `den'
		}
		drop `o'
	}
end

scalar _easi_ifkeep = 1

* ---- regenerate a brute force --------------------------------------------
if "`mode'" == "bf" {
	_t28data `case'
	local first = cond("`case'" == "a", 1, `a1')
	local last  = cond("`case'" == "a", _N, `a2')
	local out   = cond("`case'" == "a", "`DATA'/pimpute_bf_a", "`DATA'/pimpute_bf_b_`a3'")
	local eps 1e-2
	quietly easi $T28SPEC
	mata: UB = J(0, cols(st_matrix("e(b)")), .); UE = J(0, cols(st_matrix("_easi_ifkeep_e0")), .); HH = J(0, 2, .)
	forvalues h = `first'/`last' {
		quietly replace w = 1 + `eps' in `h'
		quietly easi $T28SPEC
		mata: bp = st_matrix("e(b)"); ep = st_matrix("_easi_ifkeep_e0")
		quietly replace w = 1 - `eps' in `h'
		quietly easi $T28SPEC
		mata: UB = UB \ (bp - st_matrix("e(b)")) :/ (2 * `eps'); UE = UE \ (ep - st_matrix("_easi_ifkeep_e0")) :/ (2 * `eps')
		mata: HH = HH \ (`h', 0)
		quietly replace w = 1 in `h'
	}
	mata: mata matsave "`out'" UB UE HH, replace
	scalar drop _easi_ifkeep
	exit
}

* ---- the check -------------------------------------------------------------
foreach case in a b {
	di as txt _n "`case'. " cond("`case'" == "a", "usual engine", "with selection") ///
		": analytic / brute-force standard errors"
	* without the term: the prices filled by hand, as data
	_t28data `case'
	_t28fill
	local spec0 : subinstr global T28SPEC "pimpute(grp region) " ""
	quietly easi `spec0'
	matrix __V0 = e(V)
	matrix __B0 = e(b)
	mata: IFe0 = st_matrix("_easi_ifkeep_e")
	* with it: pimpute()
	_t28data `case'
	quietly easi $T28SPEC
	matrix __V = e(V)
	mata: IFe = st_matrix("_easi_ifkeep_e")
	_chk "`case': the same estimates with pimpute() and with the prices filled by hand" `=mreldif(e(b), __B0)' 1e-10
	if "`case'" == "a" mata: mata matuse "`DATA'/pimpute_bf_a", replace
	else {
		mata: UBa = J(0, 0, .); UEa = J(0, 0, .)
		forvalues k = 1/4 {
			mata: mata matuse "`DATA'/pimpute_bf_b_`k'", replace
			mata: UBa = (rows(UBa) ? UBa \ UB : UB); UEa = (rows(UEa) ? UEa \ UE : UE)
		}
		mata: UB = UBa; UE = UEa
	}
	mata: n = rows(UB); st_numscalar("__t28n", n)
	mata: rb = sqrt(diagonal(st_matrix("__V")))' :/ sqrt(n / (n - 1) :* colsum(UB:^2))
	mata: re = sqrt(n / (n - 1) :* colsum(IFe:^2)) :/ sqrt(n / (n - 1) :* colsum(UE:^2))
	mata: st_numscalar("__t28b", max(abs(rb :- 1))); st_numscalar("__t28e", max(abs(re :- 1)))
	mata: rb0 = sqrt(diagonal(st_matrix("__V0")))' :/ sqrt(n / (n - 1) :* colsum(UB:^2))
	mata: re0 = sqrt(n / (n - 1) :* colsum(IFe0:^2)) :/ sqrt(n / (n - 1) :* colsum(UE:^2))
	mata: st_numscalar("__t28w", max(abs((rb0, re0) :- 1)))
	mata: printf("{txt}  without the term: coefficients %6.4f to %6.4f, elasticities %6.4f to %6.4f\n", min(rb0), max(rb0), min(re0), max(re0))
	mata: printf("{txt}  with the term:    coefficients %6.4f to %6.4f, elasticities %6.4f to %6.4f\n", min(rb), max(rb), min(re), max(re))
	if "`case'" == "b" _chk "b: without the term the standard errors are off (largest |ratio - 1| above 5%)" `=(__t28w <= 0.05)' 0
	_chk "`case': the brute force covers every household (`=__t28n')" `=abs(__t28n - _N)' 0
	_chk "`case': coefficients, largest |analytic / brute force - 1|" __t28b 0.003
	_chk "`case': elasticities, largest |analytic / brute force - 1|" __t28e 0.003
}
scalar drop _easi_ifkeep

di as txt _n "{hline 60}"
if ${NFAIL} == 0 di as res "test_step28: all checks passed"
else di as err "test_step28: ${NFAIL} check(s) failed"
